### ISSUE TITLE
can't install in colab

### ISSUE THREAD

**Issue by xuncpp** [facebookresearch/pytorch3d#1799]
I used method in install.md:

```
import sys
import torch
pyt_version_str=torch.__version__.split("+")[0].replace(".", "")
version_str="".join([
    f"py3{sys.version_info.minor}_cu",
    torch.version.cuda.replace(".",""),
    f"_pyt{pyt_version_str}"
])
!pip install fvcore iopath
!pip install --no-index --no-cache-dir pytorch3d -f https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/{version_str}/download.html
```

**It worked well before,but did't work today.
I print version_str is py310_cu121_pyt230.
I think pyt230 is not match.
I also can install successfully by  py310_cu121_pyt212,but in this case, the program cannot run.**

```
from pytorch3d import _C
ImportError: /usr/local/lib/python3.10/dist-packages/pytorch3d/_C.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops10zeros_like4callERKNS_6TensorEN3c108optionalINS5_10ScalarTypeEEENS6_INS5_6LayoutEEENS6_INS5_6DeviceEEENS6_IbEENS6_INS5_12MemoryFormatEEE
```

**Can anyone help me solve this problem? Thank you very much!**

**Comment by bottler** [comment]
I think this happened because colab updated to PyTorch 2.3.0 for which we didn't have a build. I have just added a build for that version_str so it should now work.

**Comment by xuncpp** [comment]
The problem is solved! Thank you very much for your prompt reply! ！

**Comment by JPPPPPF** [comment]
Hello @bottler , this issue is back on google colab, what can I do please to fix it? Thank you!

**Comment by bottler** [comment]
@JPPPPPF What's the actual version string colab wants?

**Comment by JPPPPPF** [comment]
@bottler same as the above
